import { AnimatePresence, motion } from 'framer-motion';
import { ShieldAlert, ShieldCheck, Terminal } from 'lucide-react';
import type { Transaction } from '@/app/dashboard/types';

type TransactionStreamProps = { transactions: Transaction[]; error?: string | null };

export const TransactionStream = ({ transactions, error }: TransactionStreamProps) => (
  <div className="flex-1 flex flex-col bg-black/60 border border-white/10 rounded-xl backdrop-blur-md overflow-hidden relative">
    <div className="flex justify-between items-center p-3 border-b border-white/10 bg-white/5"><div className="flex items-center gap-3"><Terminal size={14} className="text-[#ccff00]" /><span className="text-xs tracking-widest uppercase">Live Edge Event Stream</span></div><div className="flex items-center gap-2"><span className="relative flex h-2 w-2"><span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#ccff00] opacity-75" /><span className="relative inline-flex rounded-full h-2 w-2 bg-[#ccff00]" /></span><span className="text-[10px] text-[#ccff00]">WSS://CONNECTED</span></div></div>
    <div className="flex-1 overflow-y-auto no-scrollbar p-4 space-y-2">{error && <div className="border border-[#ff003c]/40 bg-[#ff003c]/10 p-3 text-xs text-[#ff003c]">SCAN API ERROR: {error}</div>}{!error && transactions.length === 0 && <div className="p-3 text-xs text-gray-500">No logged scans found for this merchant.</div>}<AnimatePresence initial={false}>{transactions.map((transaction) => <motion.div key={transaction.id} layout initial={{ opacity: 0, x: -50, backgroundColor: 'rgba(204,255,0,0.2)' }} animate={{ opacity: 1, x: 0, backgroundColor: 'rgba(0,0,0,0)' }} exit={{ opacity: 0, scale: 0.9 }} transition={{ type: 'spring', stiffness: 500, damping: 30 }} className={`flex items-center justify-between p-3 border-l-2 text-xs md:text-sm transition-colors ${transaction.status === 'FRAUD' ? 'border-[#ff003c] bg-[#ff003c]/5 hover:bg-[#ff003c]/10' : 'border-white/20 hover:border-[#ccff00]/50 hover:bg-white/5'}`}><div className="flex items-center gap-4 min-w-0"><span className="text-gray-500 w-24 shrink-0 whitespace-nowrap">[{transaction.time}]</span><span className={transaction.status === 'FRAUD' ? 'text-[#ff003c] font-bold shrink-0' : 'text-[#ccff00] shrink-0'}>{transaction.status === 'FRAUD' ? 'ERR_SPOOF' : 'SYS_AUTH'}</span><span className="text-white opacity-80 truncate">{`-> EXTRACT: ₹${transaction.amount}`}</span></div><div className="flex items-center gap-4 shrink-0"><span className="text-[10px] text-gray-600 uppercase hidden md:inline">SRC: {transaction.method}</span><span className="text-[10px] text-gray-500 hidden md:inline">ID:{transaction.id}</span>{transaction.status === 'FRAUD' ? <ShieldAlert size={16} className="text-[#ff003c] animate-pulse" /> : <ShieldCheck size={16} className="text-gray-600" />}</div></motion.div>)}</AnimatePresence></div>
  </div>
);
